### ISSUE TITLE
Random Package

### ISSUE THREAD

**Issue by SujalChoudhari** [SujalChoudhari/Coda#11]
Coda needs a Random package for generating random numbers.
It should:
- pure random numbers
- generate a random number of type int, float, double
- have functions to choose from a list
Extra: 
- seed based random numbers

Use FFI.h for the package, look at `dll/Maths` and `dll/OS` for inspiration.

**Comment by yuvrxj-afk** [comment]
Hey Sujal , Coda seems interesting.
This will lead to creating another package as  `dll/Random` or in `dll/Maths` only?
``` cpp
void coda_random(IValuePtr res, IValuePtr args, IEnvironment * env) {
    // Seed the random number generator (usually done once at the start of your program)
    static bool seeded = false;
    if (!seeded) {
        srand(static_cast<unsigned>(time(nullptr)));
        seeded = true;
    }

    // Generate a random number between 0 and 1
    double random_number = static_cast<double>(rand()) / RAND_MAX;

    res->setType(Coda::Runtime::Type::FLOAT);
    res->setValue(std::to_string(random_number));
}

```
This should be the way of creating the methods ? if not, correct me.

**Comment by SujalChoudhari** [comment]
Great!
Yes create another package called `Random`
here are some changes/feature requests:
- as mentioned above create functions that are supported by major Coda Types `Coda::Runtime::Type`
  Not all types require random function, but major types like, FLOAT, INT and LONG does.
- The dll is lazy-loaded (atleast when linux support will be added.)
![image](https://github.com/SujalChoudhari/Coda/assets/85174767/487b2b0a-d474-440a-bac7-e15390625ffe)

So if you need setting up somethings you can create a function `coda_setup` or `coda_init`
and in `Defination File` i.e. your `Random.coda`

you can manually call the functions when necessary (inside the functions or in global scope)

```js
scope random {
    def randFloat(){
    native Random coda_setup();
    return native Random coda_random();
    }
}

// OR when scope is over
native Random coda_init(params);
```

**Comment by yuvrxj-afk** [comment]
Alright ! I'll get a better understanding about coda and then move ahead in a while.

**Comment by SujalChoudhari** [comment]
Sure.
@yuvrxj-afk please fix the issues mentioned in the pr
- branch name
- merge to `dev` branch
here is the [guide](https://github.com/SujalChoudhari/Coda/blob/main/CONTRIBUTING.md)
