### ISSUE TITLE
Optimise Code with Switch Statement

### ISSUE THREAD

**Issue by SujalChoudhari** [SujalChoudhari/Coda#25]
There are few places where if-else ladder is used.
This should be replaced by switch case statements.

Positions of if-else ladder:
- [Lexer](https://github.com/SujalChoudhari/Coda/blob/0040a303decd8852c05f2914a69b1335aabb5b0c/Frontend/Lexer/Lexer.cpp#L51C1-L51C1)
- [Interpreter](https://github.com/SujalChoudhari/Coda/blob/0040a303decd8852c05f2914a69b1335aabb5b0c/Runtime/Interpreter/Interpreter.cpp#L20)

**Comment by ankits57** [comment]
hey, I want to work on this one, can you please assign this to me

**Comment by gurjott** [comment]
can you please assign me

**Comment by ankits57** [comment]
i have already created a PR for the changed code

**Comment by SujalChoudhari** [comment]
I have merged @ankits57 s PR.

@gurjott there are various other optimizations that can be performed. 
Look into that.
