### ISSUE TITLE
Linux and Mac support for Coda

### ISSUE THREAD

**Issue by SujalChoudhari** [SujalChoudhari/Coda#9]
Currently Coda is only built for Windows platform.
The code is mostly cross-platform but it needs to be tested and built for the Linux and Mac systems.

**Comment by SusheelThapa** [comment]
@SujalChoudhari  I can help to test in linux. Can you tell me the modules/packages project depend on?

**Comment by SujalChoudhari** [comment]
@SusheelThapa,
Appreciated your interest in this project.
I actually want to add the Linux and Mac support, there is no support right now. 

I was planning to add it, but due to lack of time and knowledge about these platforms I removed some parts. i.e. v1.0.1
You can view version 1 where there were traces of Linux support.

You can bring those changes back and fix some of the issues.
